### ISSUE TITLE
use eslint-config-koa

### ISSUE THREAD

**Issue by hiroppy** [koajs/body-parsers#49]
I want to use eslint-config-koa because koajs/koa uses it.

If we use it now, the following error will occur.

```
semi
arrow-parens
space-before-function-paren
padded-blocks

✖ 169 problems (169 errors, 0 warnings)
```

@jonathanong What do you think?

**Comment by jonathanong** [comment]
I don't want to maintain another eslint plugin, better to use an off-the-shelf config like standard
